#!/usr/bin/env python3
"""Lightweight dialogue-length ablation setup (R1 W1 camera-ready addition).

Produces the *inputs* for a length ablation: truncated-dialogue files (first-K
turns) plus one inference config per (model, K). No model inference here — this
step is free/local. Run the emitted configs (see printed commands) to generate
the answers, then analyse with dialogue_length_ablation_analyze.py.

Turn = one (user, chatbot) pair = 2 messages in all_samples.jsonl. Full dialogue
is K=5 (already cached), so we only add K in {1,3}.

# ponytail: hard-coded to the 3 top stereotypers + career only. That IS the
# lightweight scope; widen MODELS/DOMAIN/USERS below to scale up.
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOMAIN_DIR = "career_advice"
SRC = f"datasets/wvs_generated_dialogues/{DOMAIN_DIR}/all_samples.jsonl"
TURNS = [1, 3]          # K=5 full dialogue already cached
N_USERS = 200           # first-N slice
CONFIG_DIR = "llm_behavior_adaptation/value_measurement/values_prediction_configs/_dialogue_length_ablation"

# (config-dir name, evaluated_model, base_url, results-dir name)
MODELS = [
    ("gpt-5.1",                "gpt-5.1",                  "https://api.openai.com/v1",     "gpt-5.1"),
    ("qwen2.5-72b-instruct",   "qwen/qwen-2.5-72b-instruct", "https://openrouter.ai/api/v1", "Qwen2.5-72B-Instruct"),
    ("deepseek-v3",            "deepseek/deepseek-chat",   "https://openrouter.ai/api/v1",  "DeepSeek-V3"),
]

CONFIG_TMPL = """# Auto-generated by scripts/dialogue_length_ablation_setup.py — do not edit by hand.
user_profile_dataset_path: "datasets/wvs_benchmarks/sampled_demographic_features.csv"
dialogue_file: "{dialogue_file}"
picked_questions_path: "datasets/wvs_benchmarks/picked_questions.json"
evaluated_model: {model}
direct_output_file_path: ignore
dialogue_output_file_path: {out}
prompts_folder: llm_behavior_adaptation/value_measurement/prompts
starting_row: 0
ending_row: {n}
llm_server: llm_platform
verbose: 1
storage_step: 1
reasoning: false
model_base_url: {base_url}
run_mode: dialogue
"""


def truncate(src_path, k):
    """Write a first-K-turns copy of the dialogue file; return its path."""
    out = src_path.replace("all_samples.jsonl", f"all_samples_turns{k}.jsonl")
    n_written = kept_turns = 0
    with open(src_path) as fin, open(out, "w") as fout:
        for line in fin:
            rec = json.loads(line)
            (uid, msgs), = rec.items()          # single-key {user_id: [messages]}
            rec[uid] = msgs[: 2 * k]             # K turns = 2K messages
            kept_turns = max(kept_turns, len(rec[uid]) // 2)
            fout.write(json.dumps(rec) + "\n")
            n_written += 1
    print(f"  turns={k}: wrote {n_written} dialogues (max {kept_turns} turns) -> {out}")
    return out


def main():
    os.chdir(REPO)
    os.makedirs(CONFIG_DIR, exist_ok=True)
    commands = []
    for k in TURNS:
        dfile = truncate(SRC, k)
        for cfg_name, model, base_url, res_dir in MODELS:
            out = f"wvs_values_results/{res_dir}/career/dialogue_turns{k}_values_results/first_{N_USERS}.jsonl"
            cfg_path = f"{CONFIG_DIR}/{cfg_name}_career_turns{k}.yaml"
            with open(cfg_path, "w") as f:
                f.write(CONFIG_TMPL.format(dialogue_file=dfile, model=model, out=out, n=N_USERS, base_url=base_url))
            commands.append(f"python -m llm_behavior_adaptation.value_measurement.wvs_values_prediction --config {cfg_path}")
    print(f"\nWrote {len(commands)} configs under {CONFIG_DIR}/")
    print("\n# Run these (each spends API credits; local models via openrouter, GPT-5.1 via azure):")
    for c in commands:
        print(c)


def _selfcheck():
    """assert-based check: K-turn truncation keeps exactly 2K messages."""
    sample = {"u1": [{"role": "user", "content": "a"}, {"role": "chatbot", "content": "b"}] * 5}  # 5 turns
    for k in (1, 3):
        msgs = sample["u1"][: 2 * k]
        assert len(msgs) == 2 * k, (k, len(msgs))
        assert msgs[0]["role"] == "user" and msgs[-1]["role"] == "chatbot"
    print("selfcheck ok")


if __name__ == "__main__":
    import sys
    if "--selfcheck" in sys.argv:
        _selfcheck()
    else:
        main()
